"""
AI File Management Platform v2.0

Recommendation Engine

Purpose:
    Analyze file intelligence results and generate safe,
    explainable recommendations for the user.

Important Principles:
    - Read Only
    - Privacy First
    - Security First
    - AI First
    - Never modify files directly
    - Recommendations require controlled decisions
"""

from dataclasses import dataclass
from typing import Any, Dict, List


@dataclass
class AIRecommendation:
    """
    Represents a recommendation generated by the AI.
    """

    action: str
    reason: str
    confidence: float
    risk_level: str
    requires_confirmation: bool


class AIRecommendationEngine:
    """
    Generate recommendations from file intelligence results.

    This engine recommends actions only.
    It never performs file operations.
    """

    def generate_recommendations(
        self,
        analysis_result: Dict[str, Any],
    ) -> List[AIRecommendation]:
        """
        Generate recommendations from analyzed file data.
        """

        recommendations = []

        total_files = analysis_result.get("total_files", 0)
        categories = analysis_result.get("categories", {})

        if total_files == 0:
            return recommendations

        # Recommendation: organize documents
        document_count = categories.get("document", 0)

        if document_count >= 10:
            recommendations.append(
                AIRecommendation(
                    action="organize_documents",
                    reason=(
                        f"{document_count} document files were found. "
                        "They could be organized into a dedicated document structure."
                    ),
                    confidence=0.90,
                    risk_level="LOW",
                    requires_confirmation=True,
                )
            )

        # Recommendation: organize images
        image_count = categories.get("image", 0)

        if image_count >= 10:
            recommendations.append(
                AIRecommendation(
                    action="organize_images",
                    reason=(
                        f"{image_count} image files were found. "
                        "They could be grouped into an organized image structure."
                    ),
                    confidence=0.88,
                    risk_level="LOW",
                    requires_confirmation=True,
                )
            )

        # Recommendation: review executable files
        executable_count = categories.get("executable", 0)

        if executable_count > 0:
            recommendations.append(
                AIRecommendation(
                    action="review_executables",
                    reason=(
                        f"{executable_count} executable file(s) were found. "
                        "They should be reviewed before any management action."
                    ),
                    confidence=0.95,
                    risk_level="HIGH",
                    requires_confirmation=True,
                )
            )

        return recommendations

    @staticmethod
    def recommendation_to_dict(
        recommendation: AIRecommendation,
    ) -> Dict[str, Any]:
        """
        Convert a recommendation into a dictionary.
        """

        return {
            "action": recommendation.action,
            "reason": recommendation.reason,
            "confidence": recommendation.confidence,
            "risk_level": recommendation.risk_level,
            "requires_confirmation": recommendation.requires_confirmation,
        }